windows:
  title: "Player Movement Test"
  window:
    width: 955
    height: 720
  fps: 60
  tile_size: 32

  debug:
    DEBUG_MODE: false
    toggle_key: "K_1"   # 用名称映射到 pygame 常量

game:
  modes_allowed: ["POINT", "ONE_LIFE"]
  current_mode: "ONE_LIFE"

assets:
  base_dir: ".."
  sprites_path:
    player_1: "player/player1_sprite"
    player_2: "player/player2_sprite"
    player_3: "player/player3_sprite"
    player_4: "player/player4_sprite"
    player_5: "player/player5_sprite"
    manbo: "player/manbo_sprite"
    hajimi: "player/hajimi_sprite"

  sprites_name:
    player_1: "player1_sprite"
    player_2: "player2_sprite"
    player_3: "player3_sprite"
    player_4: "player4_sprite"
    manbo: "manbo_sprite"
    hajimi: "hajimi_sprite"

    # 可继续扩展
