tiles:
  block_orange:
    path: ../assets/sprites/background/map_base/block_orange.png
    width: 32
    height: 37
    anchor_x: 0
    anchor_y: 0
    collision: 0
  block_red:
    path: ../assets/sprites/background/map_base/block_red.png
    width: 32
    height: 37
    anchor_x: 0
    anchor_y: 0
    collision: 0
  box_wooden:
    path: ../assets/sprites/background/map_base/box_wooden.png
    width: 32
    height: 37
    anchor_x: 0
    anchor_y: 0
    collision: 0
  box_wooden2:
    path: ../assets/sprites/background/map_base/box_wooden2.png
    width: 31
    height: 30
    anchor_x: 0
    anchor_y: 0
    collision: 0
  floor_iron:
    path: ../assets/sprites/background/map_base/floor_iron.png
    width: 32
    height: 32
    anchor_x: 0
    anchor_y: 0
    collision: 0
  grass:
    path: ../assets/sprites/background/map_base/grass.png
    width: 32
    height: 32
    anchor_x: 0
    anchor_y: 0
    collision: 0
  grass_green:
    path: ../assets/sprites/background/map_base/grass_green.png
    width: 33
    height: 45
    anchor_x: 0
    anchor_y: 0
    collision: 0
  house:
    path: ../assets/sprites/background/map_base/house.png
    width: 32
    height: 32
    anchor_x: 0
    anchor_y: 0
    collision: 0
  house_blue:
    path: ../assets/sprites/background/map_base/house_blue.png
    width: 32
    height: 46
    anchor_x: 0
    anchor_y: 0
    collision: 0
  house_yellow:
    path: ../assets/sprites/background/map_base/house_yellow.png
    width: 32
    height: 46
    anchor_x: 0
    anchor_y: 0
    collision: 0
  ironbox_blue:
    path: ../assets/sprites/background/map_base/ironbox_blue.png
    width: 32
    height: 31
    anchor_x: 0
    anchor_y: 0
    collision: 0
  ironbox_lightblue:
    path: ../assets/sprites/background/map_base/ironbox_lightblue.png
    width: 32
    height: 32
    anchor_x: 0
    anchor_y: 0
    collision: 0
  ironbox_yellowandblack:
    path: ../assets/sprites/background/map_base/ironbox_yellowandblack.png
    width: 32
    height: 32
    anchor_x: 0
    anchor_y: 0
    collision: 0
  obj:
    path: ../assets/sprites/background/map_base/obj.png
    width: 256
    height: 576
    anchor_x: 0
    anchor_y: 0
    collision: 0
  obj2:
    path: ../assets/sprites/background/map_base/obj2.png
    width: 128
    height: 128
    anchor_x: 0
    anchor_y: 0
    collision: 0
  roadblock_red:
    path: ../assets/sprites/background/map_base/roadblock_red.png
    width: 31
    height: 32
    anchor_x: 0
    anchor_y: 0
    collision: 0
  road_0:
    path: ../assets/sprites/background/map_base/road_0.png
    width: 32
    height: 32
    anchor_x: 0
    anchor_y: 0
    collision: 0
  road_1:
    path: ../assets/sprites/background/map_base/road_1.png
    width: 32
    height: 32
    anchor_x: 0
    anchor_y: 0
    collision: 0
  road_2:
    path: ../assets/sprites/background/map_base/road_2.png
    width: 32
    height: 32
    anchor_x: 0
    anchor_y: 0
    collision: 0
  shadow:
    path: ../assets/sprites/background/map_base/shadow.png
    width: 32
    height: 20
    anchor_x: 0
    anchor_y: 0
    collision: 0
  tree:
    path: ../assets/sprites/background/map_base/tree.png
    width: 32
    height: 46
    anchor_x: 0
    anchor_y: 10
    collision: 0
  ground_00:
    path: ../assets/sprites/background/map_base/ground_00.png
    width: 32
    height: 32
    anchor_x: 0
    anchor_y: 0
    collision: 0
