audio:
  sounds:
    bomb: ../assets/audio/Sounds effect/bomb.mp3
    explosion: ../assets/audio/Sounds effect/explosion.mp3
    player_hit: ../assets/audio/Sounds effect/player_hit.mp3
    player_die: ../assets/audio/Sounds effect/player_die.mp3
    player_win: ../assets/audio/Sounds effect/player_win.mp3
    player_lose: ../assets/audio/Sounds effect/player_lose.mp3

  bgm:
    game_bgm: ../assets/audio/bgm/game_bgm.mp3
    bgm2: ../assets/audio/bgm/game_bgm.mp3
    bgm3: ../assets/audio/bgm/game_bgm.mp3